Document: artist-sdk
Title: Debian artist-sdk Manual
Author: <insert document author here>
Abstract: This manual describes what artist-sdk is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/artist-sdk/artist-sdk.sgml.gz

Format: postscript
Files: /usr/share/doc/artist-sdk/artist-sdk.ps.gz

Format: text
Files: /usr/share/doc/artist-sdk/artist-sdk.text.gz

Format: HTML
Index: /usr/share/doc/artist-sdk/html/index.html
Files: /usr/share/doc/artist-sdk/html/*.html
